namespace WritingIdentifier.Models
{
    public class DataModel
    {
        public object AppProperties { get; set; }
        public object Capabilities { get; set; }
        public object ContentHints { get; set; }
        public object ContentRestrictions { get; set; }
        public object CopyRequiresWriterPermission { get; set; }
        public object Description { get; set; }
        public object DriveId { get; set; }
        public object ExplicitlyTrashed { get; set; }
        public object ExportLinks { get; set; }
        public object FileExtension { get; set; }
        public object FolderColorRgb { get; set; }
        public object FullFileExtension { get; set; }
        public object HasAugmentedPermissions { get; set; }
        public object HasThumbnail { get; set; }
        public object HeadRevisionId { get; set; }
        public object IconLink { get; set; }
        public string Id { get; set; }
        public object ImageMediaMetadata { get; set; }
        public object IsAppAuthorized { get; set; }
        public object Kind { get; set; }
        public object LabelInfo { get; set; }
        public object LastModifyingUser { get; set; }
        public object LinkShareMetadata { get; set; }
        public object Md5Checksum { get; set; }
        public string MimeType { get; set; }
        public object ModifiedByMe { get; set; }
        public object ModifiedByMeTimeRaw { get; set; }
        public object ModifiedByMeTime { get; set; }
        public string Name { get; set; }
        public object OriginalFilename { get; set; }
        public object OwnedByMe { get; set; }
        public object Owners { get; set; }
        public object Parents { get; set; }
        public object PermissionIds { get; set; }
        public object Permissions { get; set; }
        public object Properties { get; set; }
        public object QuotaBytesUsed { get; set; }
        public object ResourceKey { get; set; }
        public object Sha1Checksum { get; set; }
        public object Sha256Checksum { get; set; }
        public object Shared { get; set; }
        public object SharedWithMeTimeRaw { get; set; }
        public object SharedWithMeTime { get; set; }
        public object SharingUser { get; set; }
        public object ShortcutDetails { get; set; }
        public object Size { get; set; }
        public object Spaces { get; set; }
        public object Starred { get; set; }
        public object TeamDriveId { get; set; }
        public object ThumbnailLink { get; set; }
        public object ThumbnailVersion { get; set; }
        public object Trashed { get; set; }
        public object TrashedTimeRaw { get; set; }
        public object TrashedTime { get; set; }
        public object TrashingUser { get; set; }
        public object Version { get; set; }
        public object VideoMediaMetadata { get; set; }
        public object ViewedByMe { get; set; }
        public object ViewedByMeTimeRaw { get; set; }
        public object ViewedByMeTime { get; set; }
        public object ViewersCanCopyContent { get; set; }
        public object WebContentLink { get; set; }
        public object WebViewLink { get; set; }
        public object WritersCanShare { get; set; }
        public object ETag { get; set; }
        public object FolderImage { get; set; }
        public object FolderId { get; set; }
        public object FolderName { get; set; }
    }
}
